-- models/x-form/xform_vc_returns.sql

SELECT
    vintage_year,
    asset_class,
    first_transaction_period,
    as_of_date,
    fund_count,
    irr_pooled,
    irr_equal_weighted,
    irr_capital_weighted,
    irr_average,
    irr_top_5,
    irr_upper_quartile,
    irr_median,
    irr_lower_quartile,
    irr_bottom_5,
    irr_std_dev,
    tvpi_pooled,
    tvpi_capital_weighted,
    tvpi_average,
    tvpi_top_5,
    tvpi_upper_quartile,
    tvpi_median,
    tvpi_lower_quartile,
    tvpi_bottom_5,
    tvpi_std_dev,
    dpi_pooled,
    dpi_capital_weighted,
    dpi_average,
    dpi_top_5,
    dpi_upper_quartile,
    dpi_median,
    dpi_lower_quartile,
    dpi_bottom_5,
    dpi_std_dev,
    geo_region
FROM {{ ref('base_pe_returns') }}
WHERE asset_class = 'Venture Capital'
